version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "11111:8080"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    env_file:
      - .env
