version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "11111:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - public:/var/www/html/public
    links:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - public:/var/www/html/public
    links:
      - db

  # db:
  #   image: mariadb:10.11.4-jammy
  #   container_name: db
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./data:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
  #     - MYSQL_DATABASE=${DB_DATABASE}
  #     - MYSQL_USER=${DB_USERNAME}
  #     - MYSQL_PASSWORD=${DB_PASSWORD}

volumes:
  public:
